# Generated by Django 4.0.4 on 2022-05-29 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='time_minutes',
            new_name='time_miniutes',
        ),
    ]
