# Generated by Django 4.0.4 on 2022-05-29 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_time_minutes_recipe_time_miniutes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredient',
            new_name='ingredients',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='tag',
            new_name='tags',
        ),
    ]
